# application-eureka1.yml
# 启动参数激活eureka1： --spring.profiles.active=eureka1
eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka2:2002/eureka
server:
  port: 2001