spring:
  application:
    name: turbine
# eureka2001, zuul3001, dashboard4001, 5001, 6001
server:
  port: 5001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
turbine:
  app-config: zuul
  cluster-name-expression: new String("default")